# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a501c68250d385b5865ed82bcad4d3b3e8cc712a7142eb7b7699481de822b3eb28a8e0b7801b325d1028b1f22abc3ad45cc36a24519386504a3d3e61be996f3

test:
  secret_key_base: 31352b73df962095455a2ad3b1565807db1ccb7d471de2f38f673d721dd7b806fd1f7c3602f54f7ccffbc94452b146be60352e2c6e8666b42fbc779547e2f98c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
